### ISSUE TITLE
missing index.js file

### ISSUE THREAD

**Issue by Draecona** [learn-co-curriculum/phase-0-pac-3-what-is-a-test-lab#21]
### Canvas Link

https://learning.flatironschool.com/courses/6611/assignments/224909?module_item_id=525466

### Concern

I cloned the correct lesson successfully and imported it to visual studio. However, I cannot complete the lesson because there is no index.js, only indexTest.js.

**Comment by lizbur10** [comment]
Hi @Draecona! The index.js file is present in the repo so I'm not sure why it wasn't there for you. Make sure you're looking in the root directory, not in the test folder (where indexTest.js is). You can also create it yourself (again, make sure you create it in the root directory) and copy/paste the code from the repo here on GitHub.

I'm going to go ahead and close this issue. If you are still having problems, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

I hope you're able to get this resolved!
