### ISSUE TITLE
Forgotten Reminder

### ISSUE THREAD

**Issue by kirstenleah** [learn-co-curriculum/phase-0-pac-3-what-is-a-test-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/5470/assignments/168088?module_item_id=363181

### Concern

This page needs a reminder to delete the /* and */ block commenting syntax in the index-test.js file before running learn test; this is briefly mentioned on the previous page, reading, "In the next lesson, we will remove the /* and */ so we can run the tests." However, it is not confirmed or mentioned again on this page I linked. I hesitated doing it myself particularly because the linked page read, "You should never need to make changes to test files unless a lab's instructions specifically tell you to do so." Because my learn test output was not what I expected, I eventually deleted the /* and */ from index-test.js and tried again, getting the expected output. It was fairly easy for me to diagnose, but if students take a break between the previous page and this one, they may forget the note about index-test.js being commented out. I hope this makes sense!

### Suggested Changes

Early in this page, enter a note to remove the /* and */ from the file so we can run the tests.

**Comment by AlveeM** [comment]
Hi @kirstenleah, thanks for submitting this issue.

We've updated the lab recently. We removed the comment block and students should be able to run the tests locally when they fork and clone the repo. The changes may not show up on your instance immediately but any future cohort will see the updated version.

Thank you so much for bringing up the issue and helping us improve the curriculum. We really appreciate your help!
