### ISSUE TITLE
Missing instructions lead to frustration

### ISSUE THREAD

**Issue by Stantron** [learn-co-curriculum/phase-0-pac-3-what-is-a-test-lab#8]
### Canvas Link

https://learning.flatironschool.com/courses/5703/assignments/174656?module_item_id=382279

### Concern

You specifically tell us: 
"Important: You should never need to make changes to test files unless a lab's instructions specifically tell you to do so."

However, nowhere on that page does it tell you to remove the */ from the test file. It mentioned on the previous page that the code won't run if this is still on there but on this page it doesn't say to remove it, in fact, it says the exact opposite. This means when I run the test it returns almost nothing and is very confusing. 

### Suggested Changes

Add the instruction to remove the */ from the test file

**Comment by Stantron** [comment]
I see this a new assignment that is almost exactly like the last one except it doesn't have those */ . Why download twice? Why say "if you haven't already"? if this is actually a new assignment with a different file.  I think this is confusing even if I just realized why the instruction isn't there. This should be made more clear.

**Comment by lizbur10** [comment]
Hi @Stantron ! Thanks for bringing this to our attention. I have clarified the instructions in this lesson and the previous one to make it clearer.

Thanks for helping us improve the curriculum 💙
